### ISSUE TITLE
Consumer config

### ISSUE THREAD

**Issue by mdigi14** [aineko-dev/aineko#117]
Is line 110-111 here redundant? It's not clear to me why we set `self.name` but then don't use it.
https://github.com/aineko-dev/aineko/blob/9eb368352d637ca01ca147b6759895a1d3d89335/aineko/core/dataset.py#L103-L115

**Comment by mdigi14** [comment]
I'm doing a deep dive of the Kafka setup right now, came across this. Obviously not high priority or blocking but context here would be helpful to know if I'm missing something around how we're using this class / setting config.

**Comment by Barabazs** [comment]
We're using it to describe the consumer in:
https://github.com/aineko-dev/aineko/blob/9eb368352d637ca01ca147b6759895a1d3d89335/aineko/core/dataset.py#L164-L166 and 
https://github.com/aineko-dev/aineko/blob/9eb368352d637ca01ca147b6759895a1d3d89335/aineko/core/dataset.py#L210-L214
