### ISSUE TITLE
Creating Duplicate Kafka Topic 

### ISSUE THREAD

**Issue by mdigi14** [aineko-dev/aineko#118]
Here we call `create_topics` from the `AdminClient`. Do we know if this "overwrites" topics that already exist? I can't seem to find anything conclusive based on their documentation. Would be good for us to document this internally.

https://github.com/aineko-dev/aineko/blob/9eb368352d637ca01ca147b6759895a1d3d89335/aineko/core/runner.py#L181-L214

**Comment by mdigi14** [comment]
and do we know how this works locally vs in a cloud provider like MSK?

**Comment by craycrayfish** [comment]
My understanding is that kafka will attempt to create the topic and fail if it already exists. See: https://stackoverflow.com/questions/63566725/is-it-ok-to-create-topics-that-already-exist-in-kafkajs for a related question.

**Comment by mdigi14** [comment]
@craycrayfish For context, we want to know if restarting a pipeline creates a "new" topic because it would affect the ability for a pipeline to read older messages. If the topic is "cleared" then users would not be able to read messages that were produced before the lifetime of the latest pipeline. This would mean historical access to logs would require namespacing topics with a unique value per run, then some complicated logic around querying older versions of topics.

**Comment by mdigi14** [comment]
> My understanding is that kafka will attempt to create the topic and fail if it already exists. See: https://stackoverflow.com/questions/63566725/is-it-ok-to-create-topics-that-already-exist-in-kafkajs for a related question.

I see. I think we'll need to do some experimental testing here to confirm what is happening in production.

**Comment by mdigi14** [comment]
Closing this issue because creating a duplicate topic will raise a `KafkaException`.

See: 
![image](https://github.com/aineko-dev/aineko/assets/35337224/f5f2fa24-0182-4a60-aff2-7d414e811aa4)
