### ISSUE TITLE
Docs error for aineko plugins

### ISSUE THREAD

**Issue by ricrosales** [aineko-dev/aineko#158]
In references to plugins installation we refer to the command as:
```
poetry add aineko-plugins-fastapi-server
```

When it should be:
```
poetry add aineko-plugins-nodes-fastapi-server
```

I see this in the following places:
https://plugin-docs.aineko.dev/dev/
https://plugin-docs.aineko.dev/dev/nodes/fastapi-server/
https://plugin-docs.aineko.dev/dev/nodes/websocket-client/
https://plugin-docs.aineko.dev/dev/nodes/http-poller/

**Comment by Barabazs** [comment]
Thank you for reporting it. The docs have now been updated.
