### ISSUE TITLE
Invalid author string (poetry install)

### ISSUE THREAD

**Issue by mdigi14** [aineko-dev/aineko#53]
<img width="1004" alt="Screenshot 2023-10-31 at 8 59 37 AM" src="https://github.com/aineko-dev/aineko/assets/35337224/ede70442-5aae-4bd2-af58-449c57c216eb">

Using an email with "@xyz" raises an error during the poetry install step.

**Comment by Barabazs** [comment]
Poetry requires the author string to be  `Author <email address>` and it should include the `< ` and `>` symbol.
